# Generated by Django 4.2.4 on 2023-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlostandfound', '0002_alter_pet_breed_alter_pet_name_alter_pet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], max_length=50),
        ),
    ]
